"""Initial baseline schema.

Creates all Phase 1 core tables. To keep the ORM models the single source of
truth (and avoid hand-maintained DDL drifting from the models), this baseline
revision builds the tables directly from ``Base.metadata``. Subsequent schema
changes should be incremental, autogenerated revisions:

    alembic -c infra/migrations/alembic.ini revision --autogenerate -m "..."

Revision ID: 0001_initial_baseline
Revises:
Create Date: 2026-05-29
"""

from __future__ import annotations

from alembic import op

from kospi_flow.core.models import Base

# revision identifiers, used by Alembic.
revision = "0001_initial_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Tables created by this baseline, in dependency order (dim_stock first).
_TABLE_ORDER = [
    "dim_stock",
    "fact_price_daily",
    "fact_investor_flow_daily",
    "fact_foreign_holding_daily",
    "fact_features_daily",
    "fact_ml_prediction_daily",
]


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
